perf: 增加快速执行、执行引擎、定时任务等SLI指标实现 Tencent#1101
Tencent/bk-job pull request #1117
Opened 2022-07-12 08:38 UTC by jsonwan

1. 解析接口调用类型作为Metric Tag；
2. 增加任务启动指标；
3. 增加定时任务调度延迟指标；
4. 重构部分代码。

2022-07-14 03:18 UTC, wangyu096 requested changes

2022-07-14 03:18 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/JobContextUtil.java
> +            log.info("metricTagsMap is null, init");
info日志不合适，建议换成debug或者直接删除

2022-07-14 03:18 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/java/com/tencent/bk/job/analysis/config/InterceptorConfiguration.java
> +        registry.addInterceptor(jobCommonInterceptor).addPathPatterns("/**").order(10);
1,2,3换成10,20,30的意义是？

2022-07-14 03:18 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/ApiTypeTagsContributor.java
> +    private String parseApiTypeFromUri(String uri) {
private方法一般都是在public后面的，直接放在第一个不合适

2022-07-14 03:18 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/ApiTypeTagsContributor.java
> +public class ApiTypeTagsContributor implements WebMvcTagsContributor {
当前所有的API上都有WebAPI、EsbApi、InternalAPI的注解，这里是否还有必要根据路径去判断？

2022-07-14 03:18 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/metrics/RecordTaskStartAspect.java
> +            return Tag.of(CommonMetricTags.KEY_START_STATUS, CommonMetricTags.VALUE_START_STATUS_SUCCESS);
用这里计算SLI有一个问题，比如400的场景，用户传参错误，并不应该影响到job的SLI的。但是通过getResult的方法，却变成了影响SLI。建议还是使用HttpStatus的方式

2022-07-14 09:35 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/JobContextUtil.java
> +            log.info("metricTagsMap is null, init");
已修改

2022-07-14 09:35 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/ApiTypeTagsContributor.java
> +    private String parseApiTypeFromUri(String uri) {
已修改

2022-07-14 09:39 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/ApiTypeTagsContributor.java
> +public class ApiTypeTagsContributor implements WebMvcTagsContributor {
有必要，根据路径判断是通用约定，除以上三种注解外，还有来自IAM和file-worker的调用，此外，注解的适用场景也不是针对这里，不应当混用

2022-07-14 09:47 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/metrics/RecordTaskStartAspect.java
> +            return Tag.of(CommonMetricTags.KEY_START_STATUS, CommonMetricTags.VALUE_START_STATUS_SUCCESS);
已修改为通过Interceptor解析最终HttpStatus的实现机制

2022-07-15 02:18 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/ApiTypeTagsContributor.java
> +public class ApiTypeTagsContributor implements WebMvcTagsContributor {
ok

2022-07-15 03:04 UTC, wangyu096 requested changes

2022-07-15 03:10 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/CustomTimedMetricsAutoConfiguration.java
> +    ) {
这里是因为把参数放到右侧超出了最大行长度了才换行的

2022-07-15 03:13 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/metrics/CommonMetricNames.java
> +    public static final String JOB_TASK_START = "job.task.start";
指标应该是属于内部的数据，和对外开放的接口还是不一样，这里是和TaskInstance呼应，并且job.job.start这个名字也比较奇怪，感觉这里用task还合适点

2022-07-15 03:54 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/metrics/CommonMetricNames.java
> +    public static final String JOB_CRON_SCHEDULE_DELAY = "job.cron.schedule.delay";
已处理

2022-07-15 03:54 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/metrics/CommonMetricTags.java
> + * 公共监控指标
已处理

2022-07-15 06:38 UTC, wangyu096 approved these changes

2022-07-15 06:39 UTC, merged