perf: 本地DB中缓存的无效主机定时清理 #1399
Tencent/bk-job pull request #1404
Opened 2022-09-28 09:49 UTC by jsonwan

无效主机清理

2022-09-28 11:15 UTC, wangyu096 requested changes

2022-09-28 11:15 UTC, wangyu096 commented on support-files/sql/job-manage/0026_job_manage_20220927-1000_V3.6.0_mysql.sql
> +            ADD COLUMN last_modify_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
1. 看下host.row_update_time是否已经可以满足
2. last_modify_time在其他表中都是bigint类型，看下能否统一；看了下代码逻辑中会把当前job服务器的时间跟DB更新的last_modify_time进行对比，就会要求DB和Java服务器使用同一时区

2022-09-29 04:00 UTC, jsonwan commented on support-files/sql/job-manage/0026_job_manage_20220927-1000_V3.6.0_mysql.sql
> +            ADD COLUMN last_modify_time datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
1. host.row_update_time按照约定作为辅助字段，仅用于排查DB写入延迟问题，因此不在代码中直接引用。
2. 这里是考虑到默认值，已改为新的实现方案。

2022-09-30 01:43 UTC, wangyu096 approved these changes

2022-09-30 01:43 UTC, merged