perf: 文件网关支持以File-Worker标签作为依据进行调度 #1428
Tencent/bk-job pull request #1436
Opened 2022-10-26 06:46 UTC by jsonwan

1. File-Gateway支持按标签进行调度;
2. 重构代码，消除告警。

2022-10-26 08:17 UTC, wangyu096 requested changes

2022-10-26 08:17 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/dao/filesource/impl/FileWorkerDAOImpl.java
> +        if (includeIds != null) {
应该是判断notEmpty才对吧?不然传入一个空的集合，这里就报错了

2022-10-26 08:17 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/dao/filesource/impl/FileWorkerDAOImpl.java
> +            conditions.add(defaultTable.ID.notIn(excludeIds));
应该是判断notEmpty才对吧?不然传入一个空的集合，这里就报错了

2022-10-26 08:17 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileWorkerServiceImpl.java
> +        List<String> whiteTags = fileGatewayConfig.getWorkerTagWhiteList();
如果没有配置white&black tag的场景，能否正常运行？

2022-11-09 03:34 UTC, jsonwan commented on support-files/sql/job-file-gateway/0005_job_file_gateway_20221017-1000_V3.6.1_mysql.sql
> +    UNIQUE INDEX `unique_worker_tag` (`worker_id`, `tag`) USING BTREE,
已修改

2022-11-09 03:38 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/config/FileGatewayConfig.java
> +    private List<String> workerTagWhiteList;
已添加

2022-11-09 03:38 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/config/FileGatewayConfig.java
> +    private List<String> workerTagBlackList;
已添加

2022-11-09 03:44 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileServiceImpl.java
>          log.info(String.format("url=%s,body=%s,headers=%s", fileAvailableReq.getUrl(), fileAvailableReq.getBody(),
已全部修改

2022-11-09 03:53 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/dao/filesource/impl/FileWorkerDAOImpl.java
> +        if (includeIds != null) {
mysql确实不允许空数组条件，已修改

2022-11-09 03:53 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/dao/filesource/impl/FileWorkerDAOImpl.java
> +            conditions.add(defaultTable.ID.notIn(excludeIds));
已修改

2022-11-09 04:02 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileWorkerServiceImpl.java
> +        List<String> whiteTags = fileGatewayConfig.getWorkerTagWhiteList();
已验证，可正常运行

2022-11-09 04:22 UTC, wangyu096 approved these changes

2022-11-09 06:24 UTC, merged