feature: Job对接GSE1.0/2.0支持灰度 #1602
Tencent/bk-job pull request #1621
Opened 2022-12-14 08:22 UTC by wangyu096

1. 按照与GSE讨论的灰度方案结果，简化调用GSE场景。第一种，如果走GSE1.0, 全部使用云区域+ipv4的方式，调用thrift；第二种，如果走GSE 2.0, 那么统一使用GSE 2.0 HTTP API, 传入真实的从cmdb拿到的bk_agent_id。
2. Job支持按照业务灰度对接GSE1.0/2.0(按任务权重对接影响范围较大，咱不提供）
3. 考虑到agent状态查询、任务下发、结果查询之间的关联性，对于同一个任务来说，需要调用同一个GSE。处理如下: 在TaskExecuteServiceImpl中就根据特性开关确定使用GSE1.0/2.0。如果用GSE1.0,那么设置agentId为{云区域ID:IPv4}这种兼容模式；如果用GSE2.0，那么设置agentId为真实的从cmdb获取到的bk_agent_id属性。后续的Agent状态查询/任务下发，根据agentId的版本选择下发的GSE.
4. 查询GSE任务结果使用GSE_TASK_ID判定版本（跟GSE预定，他们2.0的TASK_ID以GSE:V2:开头）
5. 重构特性开关能力，并支持通过/actuator/refresh endpoint 动态刷新配置并处理配置刷新事件（EnvironmentChangeEvent)
6. 支持动态刷新配置的能力，见 #1620 ，开发中

2022-12-14 08:54 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/config/FeatureToggleConfig.java
> +@ConfigurationProperties(prefix = "job")
记得修改所有环境的对应配置文件

2022-12-14 08:56 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/ResourceScopeTypeEnum.java
> +        throw new IllegalArgumentException("No ResourceScopeTypeEnum constant: " + type);
会破坏判断==null的代码，务必仔细检查调用该方法的逻辑

2022-12-14 11:31 UTC, jsonwan commented
请补充容器化values变更日志：support-files\kubernetes\charts\bk-job\VALUES_LOG.md
请补充周边系统依赖关系声明文件：support-files\requirements.txt

2022-12-15 03:26 UTC, jsonwan requested changes
几个问题需要看下

2022-12-15 03:30 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/config/FeatureToggleConfig.java
> +@ConfigurationProperties(prefix = "job")
ok

2022-12-15 03:34 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/ResourceScopeTypeEnum.java
> +        throw new IllegalArgumentException("No ResourceScopeTypeEnum constant: " + type);
已排查，之前代码也没有对 == null 这种返回进行处理，反而会出现空指针。后续咱们这种枚举，如果值不合法统一抛出IllegalArgumentException

2022-12-15 03:38 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/values.yaml
> +    file_manage:
已修改

2022-12-15 03:38 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/configmap-common.yaml
> +          enabled: {{ .Values.job.features.file_manage.enabled }}
已修改

2022-12-15 03:59 UTC, wangyu096 commented
> 请补充容器化values变更日志：support-files\kubernetes\charts\bk-job\VALUES_LOG.md 请补充周边系统依赖关系声明文件：support-files\requirements.txt

1. VALUES_LOG.md 已补充
2. GSE 当前暂无稳定的2.0版本，后续更新；当前的GSE 1.0 版本Job也能兼容,所以依赖上其实也是正确的

2022-12-15 04:06 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/ResourceScopeTypeEnum.java
> +        throw new IllegalArgumentException("No ResourceScopeTypeEnum constant: " + type);
ok

2022-12-15 08:02 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/VALUES_LOG.md
> +```
建议把去除的配置也声明下，否则会导致一直往配置文件中加项但不删除旧的项，日积月累后分不清哪些是有用的哪些是未用到的

2022-12-15 08:09 UTC, jsonwan commented on support-files/templates/#etc#job#job-common#application.yml
> +    file_manage:
spring的配置项风格一直都是用的中划线/驼峰形式，建议参考其他配置项/文件统一下标准

2022-12-15 08:10 UTC, jsonwan requested changes
2个问题需要继续处理下

2022-12-19 08:27 UTC, jsonwan approved these changes

2022-12-19 08:44 UTC, merged