bugfix: 依赖的其他系统（CMDB、IAM等）接口异常时报错信息优化 #1430
Tencent/bk-job pull request #1691
Opened 2023-01-12 07:03 UTC by liuliaozhong

2023-01-12 07:39 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            throw new CmdbClientException(e, ErrorCode.CMDB_API_DATA_ERROR, null);
这里异常捕获的范围太大了，会将真实的异常全部视为CMDB异常，比如因代码bug原因导致的空指针异常，只要吧外部缓存层包装的内部cause异常放出来就可以了

2023-01-12 07:59 UTC, liuliaozhong commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            throw new CmdbClientException(e, ErrorCode.CMDB_API_DATA_ERROR, null);
e不要被CmdbClientException包装，直接throw出去，由外部调用自己处理是吗

2023-01-12 09:16 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractEsbSdkClient.java
> +import com.tencent.bk.job.common.exception.CmdbClientException;
这个类是个抽象类，不止是调用CMDB的API，还可能是其他系统，这个改成Cmdb专有异常是不对的

2023-01-12 09:18 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/WebExceptionControllerAdvice.java
> +    @ExceptionHandler(CmdbClientException.class)
可以省略，处理逻辑跟其父类是一样的

2023-01-12 09:19 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/ServiceExceptionControllerAdvice.java
> +    @ExceptionHandler(CmdbClientException.class)
该方法可以省略，处理逻辑跟其父类是一样的，将来有特殊的处理逻辑时再添加

2023-01-12 09:29 UTC, jsonwan requested changes
3类问题需要处理下

2023-01-12 09:59 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            throw new CmdbClientException(e, ErrorCode.CMDB_API_DATA_ERROR, null);
这里的问题没解决，还是会把所有的异常都转为Cmdb异常，有个e.getCause()可以用，老代码的逻辑不一定是合理的，可以批判性地思考下

2023-01-12 10:00 UTC, jsonwan requested changes
第1个问题需要再处理下

2023-01-12 10:05 UTC, liuliaozhong commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            throw new CmdbClientException(e, ErrorCode.CMDB_API_DATA_ERROR, null);
确实，没考虑周全，Throwable是异常超类，会把所有异常都捕获，都当成CMDB异常

2023-01-12 12:09 UTC, liuliaozhong commented
> 3类问题需要处理下

多处地方我都没考虑周全，犯低级错误，针对修复意见定好好修改

2023-01-12 12:27 UTC, jsonwan approved these changes

2023-01-12 12:48 UTC, jsonwan requested changes
待验证通过

2023-01-12 12:53 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +                throw (RuntimeException) e;
e应当改为cause

2023-02-02 03:36 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +    public InstanceTopologyDTO getCachedBizInstCompleteTopology(long bizId){
代码格式规范里面是有空格的，确认下提交前是否对代码进行了格式化，如果有，看下是idea的格式设置问题还是误删除了空格

2023-02-02 03:40 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +    public InstanceTopologyDTO getCachedBizInstCompleteTopology(long bizId){
多名开发者之间的代码格式规范需要保持一致，否则容易引起不必要的代码改动和合并冲突

2023-02-02 03:45 UTC, jsonwan commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/client/EsbIamClient.java
> +import com.tencent.bk.job.common.exception.InternalCmdbException;
这里为什么会引入CMDB的异常，检查下是否格式化代码，去除无效引用

2023-02-02 03:54 UTC, jsonwan commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/interceptor/AuthAppInterceptor.java
> +                    throw e;
捕获异常后又立即抛出，是否是多余的代码？

2023-02-02 03:57 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/exception/InternalUserInfoException.java
> +public class InternalUserInfoException extends InternalException {
UserInfo这个名称不太合适，这个异常的目的是要指出依赖的哪一个第三方系统出了问题，叫UserManage更合适

2023-02-02 04:06 UTC, jsonwan commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/web/service/impl/LoginServiceImpl.java
> +                throw new InternalUserInfoException("Query userinfo from paas fail", e,
逻辑不对，会将其他类型异常全部当做InternalUserInfoException，这里应该抛内部服务器错误的异常

2023-02-02 04:07 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/notify/impl/NotifyEsbChannelDAOImpl.java
> +            throw new InternalCmsiException(errorMsg, e, ErrorCode.CMSI_MSG_CHANNEL_DATA_ERROR);
逻辑不对，会将其他类型异常全部当做InternalCmsiException，这里参考其他缓存异常的处理方式

2023-02-02 04:15 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +                throw new InternalCmdbException(e, ErrorCode.INTERNAL_ERROR, null);
逻辑不对，会将其他类型异常全部当做InternalCmdbException，这里应该抛内部服务器错误的异常

2023-02-02 04:17 UTC, jsonwan commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/client/EsbIamClient.java
> +            throw new InternalIamException(e, ErrorCode.IAM_API_DATA_ERROR, null);
当前IAM_API_DATA_ERROR对应的错误码信息不准确，改为：IAM接口数据异常

2023-02-02 04:20 UTC, jsonwan requested changes
几个问题需要处理下

2023-02-02 06:59 UTC, liuliaozhong commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +                throw new InternalCmdbException(e, ErrorCode.INTERNAL_ERROR, null);
这样的话，原本CmdbException异常也变成内部服务器异常了
![image](https://user-images.githubusercontent.com/120009833/216253926-8ae4ad6d-501d-48da-b10d-3b33a94920b8.png)
这样行不行呢？

2023-02-02 09:35 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +                throw new InternalException(e, ErrorCode.CMDB_API_DATA_ERROR, null);
errorCode应该是ErrorCode.INTERNAL_ERROR

2023-02-02 09:37 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/notify/impl/NotifyEsbChannelDAOImpl.java
> +                throw new InternalException(errorMsg, e, ErrorCode.CMSI_MSG_CHANNEL_DATA_ERROR);
errorCode应该是ErrorCode.INTERNAL_ERROR

2023-02-02 09:38 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +                throw new InternalCmdbException(e, ErrorCode.INTERNAL_ERROR, null);
已在群内沟通

2023-02-02 09:48 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/notify/impl/NotifyEsbChannelDAOImpl.java
> +                throw new InternalException(errorMsg, e, ErrorCode.CMSI_MSG_CHANNEL_DATA_ERROR);
已修改

2023-02-02 09:49 UTC, liuliaozhong commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +                throw new InternalException(e, ErrorCode.CMDB_API_DATA_ERROR, null);
已修改

2023-02-02 10:20 UTC, jsonwan approved these changes

2023-02-02 13:41 UTC, jsonwan approved these changes

2023-02-02 13:41 UTC, merged