perf: Job 支持配置实时刷新 #1620
Tencent/bk-job pull request #1702
Opened 2023-02-01 02:40 UTC by wangyu096

1. Job 二进制环境，通过spring cloud config + spring cloud bus, 实现配置的运行时刷新
2. Job容器环境，通过  [Spring Cloud Kubernetes Configuration Watcher](https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.4/reference/html/#spring-cloud-kubernetes-configuration-watcher)](https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.4/reference/html/#spring-cloud-kubernetes-configuration-watcher) 实现配置的运行时刷新
3. 修复容器环境中配置变更，涉及的pod没有被重启的问题（原来的annotation位置错误，不会重启)
4. 重构配置监听+特性开关配置重载的代码
5. 由于spring cloud bus 中使用的 spring cloud stream 是基于 spring cloud function来配置MQ的消息监听, 无法与job-execute当前的实现（基于StreamListerer的方式）兼容，所以修改job-execute的spring cloud stream用法，也使用function的方式来配置. 参考文档: [spring cloud stream function](https://docs.spring.io/spring-cloud-stream/docs/3.1.3/reference/html/spring-cloud-stream.html#spring_cloud_function)
6. 统一使用spring cloud stream 替换原始的springboot rabbitmq的使用方式
7. 删除强制指定spring cloud function 为3.2.8（版本不匹配，运行时报错), 后续升级spring + springboot + spring cloud 框架解决 #1701

2023-02-01 07:46 UTC, jsonwan commented on src/backend/build.gradle
> +//    set('spring-cloud-function.version', "3.2.8")
这里会放出漏洞，被安全扫描到会要求强制整改，到时候时间期限上会很紧张，比较被动，建议进一步寻找其他方式解决或升级框架处理。

2023-02-01 07:51 UTC, jsonwan commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/ConfigRefreshEventListener.java
> +     * 重载特型开关配置
错别字：特性

2023-02-01 08:26 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/job-analysis/configmap.yaml
> +                    virtual-host: {{ include "job.rabbitmq.vhost" . }}
多个微服务都有这一段几乎完全相同的代码，重复了多次，能否放到configmap-common中

2023-02-01 09:01 UTC, jsonwan commented on support-files/templates/#etc#job#application-config.yml
> +                virtual-host: __BK_JOB_RABBITMQ_VHOST__
是否可以提取到公共配置文件中

2023-02-01 09:02 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> +      memory: 256Mi
请增加相应的values变更日志

2023-02-01 09:03 UTC, jsonwan commented on support-files/templates/#etc#job#job-manage#job-manage.yml
> -    virtual-host: __BK_JOB_MANAGE_RABBITMQ_VHOST__
环境变量的变动需要与运维对齐

2023-02-01 09:04 UTC, jsonwan commented on support-files/templates/#etc#job#job-execute#job-execute.yml
> -    virtual-host: __BK_JOB_EXECUTE_RABBITMQ_VHOST__
环境变量的变动需要与运维对齐

2023-02-01 09:05 UTC, jsonwan requested changes
几个问题需要处理下。

2023-02-01 09:13 UTC, wangyu096 commented on support-files/templates/#etc#job#application-config.yml
> +                virtual-host: __BK_JOB_RABBITMQ_VHOST__
不可以的。这个是spring cloud config 的配置文件，spring cloud config微服务启用要先加载这个配置文件才能启动的。公共配置文件是给除了spring cloud config的微服务使用的

2023-02-01 09:14 UTC, wangyu096 commented on support-files/templates/#etc#job#job-manage#job-manage.yml
> -    virtual-host: __BK_JOB_MANAGE_RABBITMQ_VHOST__
ok，这个后续跟运维对齐

2023-02-01 09:14 UTC, wangyu096 commented on support-files/templates/#etc#job#job-execute#job-execute.yml
> -    virtual-host: __BK_JOB_EXECUTE_RABBITMQ_VHOST__
ok，这个后续跟运维对齐

2023-02-01 09:14 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/ConfigRefreshEventListener.java
> +     * 重载特型开关配置
ok

2023-02-01 09:15 UTC, wangyu096 commented on src/backend/build.gradle
> +//    set('spring-cloud-function.version', "3.2.8")
ok，整体升级spring 框架到java8 支持的最新稳定版本

2023-02-15 06:28 UTC, jsonwan approved these changes

2023-02-21 01:35 UTC, merged