perf: 升级spring + springboot + spring cloud 框架版本 #1701
Tencent/bk-job pull request #1753
Opened 2023-02-21 01:37 UTC by wangyu096

2023-02-21 02:41 UTC, jsonwan commented on src/backend/commons/common-otel/src/main/java/com/tencent/bk/job/common/tracing/OtelConfiguration.java
> + * <p>在跑测试用例启动是，会启动spring容器，会多次初始化OtelConfiguration。由于OtelConfiguration.otel()->OtelConfiguration.otel()
错别字，应为“启动时”

2023-02-21 02:44 UTC, jsonwan commented on src/backend/commons/common-utils/src/main/java/com/tencent/bk/job/common/util/json/JsonMapper.java
> +//        mapper.registerModule(new JavaTimeModule());
这里为什么加了又注释掉

2023-02-21 03:14 UTC, jsonwan commented on src/backend/job-config/src/main/resources/logback-spring.xml
> +<?xml version="1.0" encoding="UTF-8"?>
config不复用公共的日志配置基础文件的原因是？

2023-02-21 04:07 UTC, jsonwan commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/inner/ServiceCronJobResource.java
> +    @GetMapping("/service/app/{appId}/cron/job")
非幂等修改，末尾不加斜杠是不同的接口

2023-02-21 04:08 UTC, jsonwan requested changes
几个小问题需要处理下

2023-02-21 04:10 UTC, jsonwan commented
企业版打包失败与CodeCC问题需要处理。

2023-02-21 04:28 UTC, wangyu096 commented on src/backend/job-config/src/main/resources/logback-spring.xml
> +<?xml version="1.0" encoding="UTF-8"?>
日志配置基础文件在common-service。目前的模块依赖关系，config还不能依赖common-service，会额外连锁引入很多不必要的依赖（主要在common模块中)。后续梳理下整个项目模块之间的依赖再统一。本次暂不处理

2023-02-21 06:27 UTC, wangyu096 commented on src/backend/commons/common-otel/src/main/java/com/tencent/bk/job/common/tracing/OtelConfiguration.java
> + * <p>在跑测试用例启动是，会启动spring容器，会多次初始化OtelConfiguration。由于OtelConfiguration.otel()->OtelConfiguration.otel()
fixed

2023-02-21 06:37 UTC, wangyu096 commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/inner/ServiceCronJobResource.java
> +    @GetMapping("/service/app/{appId}/cron/job")
1. 改成现有的url，现在的url更合理
2. 这个api仅被job-analysis调用，用于分析定时任务的状况。发布期间影响可控。

2023-02-21 06:41 UTC, wangyu096 commented on src/backend/commons/common-utils/src/main/java/com/tencent/bk/job/common/util/json/JsonMapper.java
> +//        mapper.registerModule(new JavaTimeModule());
多余代码，已删除。对于LocalDateTime在json中的支持，只需要findAndAddModules被调用即可。

https://stackoverflow.com/questions/21384820/is-there-a-jackson-datatype-module-for-jdk8-java-time

2023-02-22 01:55 UTC, jsonwan commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/inner/ServiceCronJobResource.java
> +    @GetMapping("/service/app/{appId}/cron/job")
ok

2023-02-22 01:59 UTC, merged