perf: Job 微服务日志优化 #1742
Tencent/bk-job pull request #1758
Opened 2023-02-22 02:15 UTC by wangyu096

#1742 
- logback配置文件模板变更
1. 为了避免在所有微服务中输出多余的日志文件(比如iam.log,esb_job.log,esb_client.log等日志不是在所有微服务中都有)，在common-service中定义logback配置文件的公共部分，各微服务的logback文件自己include进来。

- 规范部分日志文件的文件名
1. esb_job.log -> openapi.log。考虑到后续会逐步废弃esb，使用api gateway。openapi的表述更加合理
2. esb_client.log -> gse.log/cmdb.log/iam.log。由于对于的iam，gse，cmdb会输出大量日志，所以分开会更加合理和方便问题定位

- 优化第三方API日志打印，减少多余，重复的日志输出
1. 基础http client 不实用info日志（比如AbstractBkApiClient），统一交给上层的GSEClient/CmdbClient等打印，避免重复日志

2023-02-22 02:26 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +            <totalSizeCap>100GB</totalSizeCap>
权限数据时效性比较强，有问题一般很快就会收到反馈，没有必要保留过长时间的日志，这里增加日志量可能会导致磁盘空间不足，引起运维侧的调整

2023-02-22 02:34 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractBkApiClient.java
> -                JsonUtils.toJsonWithoutSkippedFields(body), (System.currentTimeMillis() - start), responseBody);
不建议改成debug级别，该日志在排查问题时经常被用到，手动开启Debug的过程影响问题排查效率

2023-02-22 02:35 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +            <totalSizeCap>100GB</totalSizeCap>
拆分后总量限制需要调整，否则可能导致磁盘空间不足

2023-02-22 02:36 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
>              <totalSizeCap>100GB</totalSizeCap>
拆分后总量限制需要调整，否则可能导致磁盘空间不足

2023-02-22 02:38 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -            <appender-ref ref="esb-client-appender"/>
拆分后其他非CMDB、GSE的ESB接口（如用户管理、权限中心ESB接口）的日志会打在哪里？与程序主日志混在一起是不妥的，需要考虑

2023-02-22 02:39 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -            <appender-ref ref="esb-client-appender"/>
拆分后其他非CMDB、GSE的ESB接口（如用户管理、权限中心ESB接口）的日志会打在哪里？与程序主日志混在一起是不妥的，需要考虑

2023-02-22 02:39 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -        <logger name="com.tencent.bk.job.common.esb" level="DEBUG" additivity="false">
拆分后其他非CMDB、GSE的ESB接口（如用户管理、权限中心ESB接口）的日志会打在哪里？与程序主日志混在一起是不妥的，需要考虑

2023-02-22 02:39 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -        <logger name="com.tencent.bk.job.common.esb" level="INFO" additivity="false">
拆分后其他非CMDB、GSE的ESB接口（如用户管理、权限中心ESB接口）的日志会打在哪里？与程序主日志混在一起是不妥的，需要考虑

2023-02-22 02:50 UTC, jsonwan requested changes
几个问题需要处理下

2023-02-22 02:51 UTC, jsonwan commented
CI失败需要处理

2023-02-22 03:14 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractBkApiClient.java
> -                JsonUtils.toJsonWithoutSkippedFields(body), (System.currentTimeMillis() - start), responseBody);
1. 基础http服务不能打印info，特别是接入gse之后会导致日志量输出量增加一个数量级
2. 这里的日志，由各个client自行打印出来

2023-02-22 03:14 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +            <totalSizeCap>100GB</totalSizeCap>
1. iam 日志比较少
2. 方便追溯问题，调整为7天

2023-02-22 04:20 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +            <totalSizeCap>100GB</totalSizeCap>
fixed

2023-02-22 04:21 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +            <totalSizeCap>100GB</totalSizeCap>
统一调整为7天，最大占用容量之前版本就是100GB

2023-02-22 04:21 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
>              <totalSizeCap>100GB</totalSizeCap>
统一调整为7天，最大占用容量之前版本就是100GB

2023-02-22 04:22 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -            <appender-ref ref="esb-client-appender"/>
fixed。按照第三方系统组织日志，分别拆分到gse.log/cmdb.log/iam.log/paas.log

2023-02-22 04:22 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -            <appender-ref ref="esb-client-appender"/>
fixed。按照第三方系统组织日志，分别拆分到gse.log/cmdb.log/iam.log/paas.log

2023-02-22 04:22 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -        <logger name="com.tencent.bk.job.common.esb" level="DEBUG" additivity="false">
fixed。按照第三方系统组织日志，分别拆分到gse.log/cmdb.log/iam.log/paas.log

2023-02-22 04:22 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> -        <logger name="com.tencent.bk.job.common.esb" level="INFO" additivity="false">
fixed。按照第三方系统组织日志，分别拆分到gse.log/cmdb.log/iam.log/paas.log

2023-02-27 03:27 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractBkApiClient.java
> +            requestApiAndWrapResponse(HttpMethod.POST, apiContext, typeReference, httpHelper);
不建议使用“导出参数”来接收返回数据，降低代码可读性

2023-02-27 03:33 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractEsbSdkClient.java
> +            requestEsbApi(apiContext, typeReference, httpHelper);
建议不使用“导出参数”

2023-02-27 03:37 UTC, jsonwan reviewed
2个建议请看下

2023-02-27 06:42 UTC, closed without merging