perf: API请求响应优化
Tencent/bk-job pull request #390
Opened 2021-11-08 10:00 UTC by wangyu096

1. web/internal api 使用 http code 表示错误， esb API 暂时保持不变
2. 标准化返回数据结构，Response作为外部协议，InternalResponse作为内部微服务间调用协议,EsbResp作为ESB API 的协议
3. 定义标准错误码以及异常，参考谷歌API协议，更加简练(https://cloud.google.com/apis/design/errors?hl=zh-cn)
4. 修改全局异常处理代码（ExceptionControllerAdvice）
5. 内部微服务调用，响应结果封装与异常错误传递(FeignErrorDecoder)
6. 基于spring validator实现参数校验框架
7. 兼容性，不破坏之前版本API的返回协议

2021-11-08 10:10 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +                throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
bug，少了括号

2021-11-08 23:05 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +                throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
嗯，这里有问题，我改下

2021-11-09 00:55 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +                throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 02:10 UTC, jsonwan commented
Response考虑改为WebResponse更好一点？InternalResponse与EsbResp都有域前缀

2021-11-09 03:05 UTC, jsonwan requested changes

2021-11-09 03:39 UTC, wangyu096 commented on src/backend/commons/paas-sdk/src/main/java/com/tencent/bk/job/common/paas/user/EEPaasClient.java
> +            log.error("Get {} error, response is null or response code is not success", API_GET_NOTIFY_CHANNEL_LIST);
建议还是不要把这种内部详细错误返回给调用方。理由：
1. 有些是内部细节，可能会有敏感信息
2. 用户根本不应该关心底层实现，比如这些通知能力是谁提供的，报了什么具体的错误，这些东西对用户来说没有任何价值，因为不能协助用户解决什么问题；这些信息仅对job的开发有点价值，可以查看日志就可以发现问题

2021-11-09 03:40 UTC, wangyu096 commented on src/backend/commons/paas-sdk/src/main/java/com/tencent/bk/job/common/paas/user/EEPaasClient.java
> +            log.error("Get {} error, response is null", API_GET_NOTIFY_CHANNEL_LIST);
fixed

2021-11-09 03:44 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 03:44 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 03:47 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/ErrorCode.java
> +    public static final int ILLEGAL_PARAM_WITH_REASON = 1241012;
这种异常不好理解，不够友好，感觉不像是针对用户的错误提示

2021-11-09 03:47 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 03:47 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 03:51 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/ErrorCode.java
> +    // 接入点响应异常：ListBucket，详情：{0}
fixed

2021-11-09 04:03 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 04:04 UTC, wangyu096 commented on src/backend/commons/paas-sdk/src/main/java/com/tencent/bk/job/common/paas/user/EEPaasClient.java
> +            log.error("Get {} error, response is null or response code is not success", API_GET_NOTIFY_CHANNEL_LIST);
更底层的细节，后续可能考虑脱敏，然后通过Response的ErrorDetail返回，但是不会直接提示给用户

2021-11-09 06:21 UTC, wangyu096 commented on src/backend/commons/paas-sdk/src/main/java/com/tencent/bk/job/common/paas/user/EEPaasClient.java
> +                log.error("Get {} error, response is null", API_POST_SEND_MSG);
fixed

2021-11-09 06:47 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2021-11-09 06:51 UTC, wangyu096 commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/EsbCcClient.java
> +        }
fixed

2021-11-09 06:52 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/interceptor/AuthAppInterceptor.java
> +//        }
fixed

2021-11-09 06:57 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +    private com.tencent.bk.job.common.iam.model.PermissionActionResource createOrGetPermissionActionResource(
fixed

2021-11-09 06:57 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +        com.tencent.bk.job.common.iam.model.PermissionActionResource actionResource =
fixed

2021-11-09 06:57 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +            com.tencent.bk.job.common.iam.model.PermissionActionResource actionResource =
fixed

2021-11-09 06:57 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +    private List<com.tencent.bk.job.common.iam.model.PermissionActionResource> requiredActionResources =
fixed

2021-11-09 06:57 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +        for (com.tencent.bk.job.common.iam.model.PermissionActionResource existedActionResource :
fixed

2021-11-09 06:58 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +    private static com.tencent.bk.sdk.iam.dto.PathInfoDTO toIamPathInfoDTO(PathInfoDTO pathInfo) {
这里使用全限定名是因为确实有冲突，这里需要指定的

2021-11-09 06:58 UTC, wangyu096 commented on src/backend/commons/common-iam/src/main/java/com/tencent/bk/job/common/iam/model/AuthResult.java
> +            com.tencent.bk.sdk.iam.util.PathBuilder.newBuilder(pathInfo.getType(), pathInfo.getId());
这里使用全限定名是因为确实有冲突，这里需要指定的

2021-11-09 07:04 UTC, merged