perf: file-worker容器化环境支持水平扩容 #436
Tencent/bk-job pull request #438
Opened 2021-11-18 13:13 UTC by jsonwan

2021-11-18 14:35 UTC, wangyu096 requested changes

2021-11-18 14:36 UTC, wangyu096 commented
后续提pr的时候，如果是比较复杂的方案，建议可以在评论里边把大概的设计方案描述下

2021-11-19 02:07 UTC, jsonwan commented on src/backend/job-file-gateway/api-job-file-gateway-worker/src/main/java/com/tencent/bk/job/file_gateway/model/req/inner/OffLineAndReDispatchReq.java
> +    @ApiModelProperty(value = "访问worker使用的host", required = true)
已修改

2021-11-19 02:45 UTC, jsonwan commented on src/backend/job-file-worker-sdk/service-job-file-worker-sdk/src/main/java/com/tencent/bk/job/file/worker/cos/service/OpService.java
>              log.info(String.format("url=%s,body=%s,headers=%s", url, req.getBody(),
已处理

2021-11-19 02:46 UTC, jsonwan commented on src/backend/job-file-worker-sdk/service-job-file-worker-sdk/src/main/java/com/tencent/bk/job/file/worker/cos/service/OpService.java
>              log.info(String.format("url=%s,body=%s,headers=%s", url, req.getBody(),
已修改

2021-11-19 02:48 UTC, jsonwan commented on src/backend/job-file-gateway/api-job-file-gateway-worker/src/main/java/com/tencent/bk/job/file_gateway/model/req/inner/OffLineAndReDispatchReq.java
> +    @ApiModelProperty(value = "访问worker使用的host", required = true)
> 后续提pr的时候，如果是比较复杂的方案，建议可以在评论里边把大概的设计方案描述下

这里的主要目的是要让file-gateway能够访问特定某一个file-worker，需要对每一个file-worker进行路由，方案采用k8s headless service+statefulset 实现，file-worker由accessHost+accessPort保证唯一性。

2021-11-19 02:49 UTC, jsonwan commented
这里的主要目的是要让file-gateway能够访问特定某一个file-worker，需要对每一个file-worker进行路由，方案采用k8s headless service+statefulset 实现，file-worker由accessHost+accessPort保证唯一性。

2021-11-19 03:02 UTC, merged