fix: 实例资源不存在时，权限中心回调接口报500错误 #448
Tencent/bk-job pull request #449
Opened 2021-11-22 11:39 UTC by jsonwan

2021-11-25 02:18 UTC, wangyu096 requested changes

2021-11-25 02:18 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/IamCallbackExceptionControllerAdvice.java
> +        responseDTO.setMessage(ex.getMessage());
直接把exception的message返回，可能会有敏感信息

2021-11-25 02:18 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/IamCallbackExceptionControllerAdvice.java
> +        return new ResponseEntity<>(responseDTO, HttpStatus.OK);
考虑下返回500？可以跟IAM对下协议，尽量使用规范的Restful的API。这样子也方便我们能监控到回调异常

2021-11-29 03:22 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/IamCallbackExceptionControllerAdvice.java
> +        return new ResponseEntity<>(responseDTO, HttpStatus.OK);
已修改

2021-11-29 03:22 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/IamCallbackExceptionControllerAdvice.java
> +        responseDTO.setMessage(ex.getMessage());
已修改

2021-11-29 08:28 UTC, wangyu096 approved these changes

2021-11-29 08:28 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/exception/handler/IamCallbackExceptionControllerAdvice.java
> +        return new ResponseEntity<>(EsbResp.buildCommonFailResp(ex), HttpStatus.OK);
400 BadRequest

2021-11-29 08:28 UTC, merged