perf: 制品库与服务器临时文件清理 #501
Tencent/bk-job pull request #508
Opened 2021-12-06 12:34 UTC by jsonwan

1.清理用户上传至制品库/本地NFS的本地文件；
2.清理因分发需要而下载到服务器的临时文件；
3.清理制品库/本地NFS中的执行日志导出临时文件；
4.清理导出作业时在本地产生的临时文件。

2021-12-07 02:25 UTC, wangyu096 requested changes

2021-12-07 02:25 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/task/LogExportFileCleanTask.java
> +    ) {
括号换行需要与之前规定的保持一致，尽量不要出现两种风格

2021-12-07 02:25 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/task/LogExportFileCleanTask.java
> +    /**
private方法不需要使用文档注释

2021-12-08 02:06 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/task/LogExportFileCleanTask.java
> +    ) {
已修改

2021-12-08 02:17 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/task/LogExportFileCleanTask.java
> +    /**
参考spring等框架，可用文档注释

2021-12-08 02:42 UTC, merged