perf: 容器化各微服务日志存储采用PVC，避免日志量过大导致Pod被驱逐 #507
Tencent/bk-job pull request #516
Opened 2021-12-08 02:45 UTC by jsonwan

直接向容器内打印日志存在问题，量比较大时会导致系统路径下占用存储过多而使Pod被驱逐，改用PV-PVC指定日志存储位置

2021-12-08 03:46 UTC, wangyu096 requested changes

2021-12-08 03:46 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/pvc-storage.yaml
> +  name: bk-job-pv-claim
需要一些通用的label和annotation，比如：
{{- include "common.labels.standard" . | nindent 4 }}

2021-12-08 03:46 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/pv-default.yaml
> +  labels:
需要一些通用的label和annotation，比如：
{{- include "common.labels.standard" . | nindent 4 }}

2021-12-08 03:46 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/pv-default.yaml
> +  name: bk-job-local-volume
name: bk-job-local-volume 可以去掉 “-volumn”，会简练点儿，另外也更符合常规习惯

2021-12-13 09:53 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/pvc-storage.yaml
> +  name: bk-job-pv-claim
已修改

2021-12-13 09:53 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/pv-default.yaml
> +  labels:
已修改

2021-12-13 09:53 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/pv-default.yaml
> +  name: bk-job-local-volume
已修改

2021-12-14 01:09 UTC, wangyu096 approved these changes

2021-12-14 01:10 UTC, merged