perf: CMDB API调用指标统计去除反序列化时间，增加IAM、用户管理等ESB接口调用指标 #528
Tencent/bk-job pull request #562
Opened 2021-12-24 13:26 UTC by jsonwan

1.重构HttpHelper相关代码，多种不同类型HttpHelper使用工厂创建；
2.底层调用增加http_status与耗时监控；
3.给ESB的登录、用户管理、消息通知、权限等接口增加监控指标。

2021-12-27 04:16 UTC, wangyu096 requested changes

2021-12-27 04:16 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/http/WatchableHttpHelper.java
> +            AbstractList<Tag> httpMetricTags = JobContextUtil.getHttpMetricTags();
感觉这个地方用JobContext的设计不太好。原因如下：
1. 如果一个线程的操作中，请求多个API，那么这里会有问题不？
2. 上下文这东西容易在代码过程中被清理（换句话说，不好控制）。而底层的方法直接依赖的JobContext里边的必须属性，虽然可能最终能用，但是感觉设计上并不太合理
3. 这些metricName和tag是否可以直接通过方法传入?

2021-12-27 04:21 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/ApiUtil.java
> +    public static String getApiNameByUri(Map<String, String> interfaceNameMap, String uri) {
对“应该”的实测结果：有/的标签会使得从标签中提取变量用于复制图表时出现问题，这里可能是个坑，直接规避掉

2021-12-27 04:26 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/metrics/CommonMetricNames.java
> +    public static final String ESB_CMDB_API = "job.client.cmdb.api";
1.http体现的是http请求过程本身，就不包含反序列化了；
2.反序列化是需要统计的，比如某些错误或超频的状态需要通过ESB_RESP_CODE来确定，这需要在反序列化之后才能拿到；
3.现在是在以前的统计指标基础上增加了更底层的http_code统计，现在是增加了一类比以前统计指标更简单的指标。

2021-12-27 04:30 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/http/WatchableHttpHelper.java
> +            AbstractList<Tag> httpMetricTags = JobContextUtil.getHttpMetricTags();
这里是考虑过的：
1.当前架构下，一个线程同一时间只能请求一个API，指标在API入口处控制，请求前设置，请求完成后就清理；
2、3.类似AOP的思想，主要是不想把指标随着调用层层传递到底层，增加代码修改的复杂度，日志监控类的辅助功能参数，最好不与业务参数混在一起。

2021-12-27 09:44 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/ApiUtil.java
> +    public static String getApiNameByUri(Map<String, String> interfaceNameMap, String uri) {
这里Premetheus的标签的值确实是支持/的，复制图表出现问题是其他原因。

2021-12-28 01:37 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/http/WatchableHttpHelper.java
> +            AbstractList<Tag> httpMetricTags = JobContextUtil.getHttpMetricTags();
ok

2021-12-28 01:38 UTC, wangyu096 approved these changes

2021-12-28 01:38 UTC, merged