perf: 根据一定规则（如指定业务ID或任务ID）将异常任务驱逐出执行引擎，使系统恢复可用 #520
Tencent/bk-job pull request #591
Opened 2022-01-01 13:25 UTC by jsonwan

1.使用策略模式实现根据AppId、AppCode进行任务驱逐，策略之间可使用AND/OR进行组合；
2.驱逐策略存放于Redis中，由加载线程定时向内存中加载，应对高并发访问；
3.两个驱逐点：
（1）阻止任务提交，不再产生新的任务实例；
（2）轮询GSE及拉取日志循环中检测驱逐状态，对符合条件的任务进行驱逐，停止调度并置为放弃执行状态。
4.实现策略查询、修改与清理的管理service接口。

2022-01-05 01:16 UTC, wangyu096 requested changes

2022-01-05 01:16 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/evict/TaskEvictPolicyManager.java
> +            policyJsonStr = loadedPolicyJsonStr;
loadedPolicyJsonStr可能为null，是否需要处理下？

2022-01-05 01:16 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +            return true;
直接return，但是没有对watch进行stop；后续如果直接对watch.start,会报错

2022-01-05 01:16 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +            if (checkAndEvictTaskIfNeed(watch)) return;
建议不要用这种简写，把{}加上

2022-01-05 01:16 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +    private boolean pullGSELogs(StopWatch watch) {
这里不只是拉取GSE日志，还有结果处理。方法命名不对

2022-01-05 01:30 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/inner/ServiceTaskEvictPolicyResource.java
> +    @ApiOperation(value = "清除任务驱逐策略", produces = "application/json")
有更新接口可以更新，这里只是一个快捷操作。

2022-01-14 12:20 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/RedisConstants.java
> +    public static final String KEY_EXECUTE_TASK_EVICT_POLICY = "taskEvictPolicy";
已修改

2022-01-14 12:49 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/inner/ServiceTaskEvictPolicyResource.java
> +    @PostMapping("/clear")
方法已改为Delete，clear不能省略，用于区分删除部分与删除全部

2022-01-14 12:53 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/StringUtil.java
> +    public static boolean isChanged(String oldStr, String newStr) {
已修改命名

2022-01-14 12:54 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/common/constants/RunStatusEnum.java
> +    CONFIRM_TERMINATED(13, "确认终止"), EVICTED(14, "放弃执行");
已修改

2022-01-14 12:58 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/evict/TaskEvictPolicyManager.java
> +            policyJsonStr = loadedPolicyJsonStr;
已处理

2022-01-14 12:59 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +            if (checkAndEvictTaskIfNeed(watch)) return;
已修改

2022-01-14 13:00 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +            return true;
已修改

2022-01-14 13:03 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +    private boolean pullGSELogs(StopWatch watch) {
已修改

2022-01-14 13:03 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/inner/ServiceTaskEvictPolicyResource.java
> +    @PostMapping("/set")
已修改

2022-01-14 13:12 UTC, wangyu096 commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/inner/ServiceTaskEvictPolicyResource.java
> +    @PostMapping("/clear")
ok

2022-01-14 13:12 UTC, wangyu096 commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/common/constants/RunStatusEnum.java
> +    CONFIRM_TERMINATED(13, "确认终止"), EVICTED(14, "放弃执行");
ok

2022-01-14 13:12 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/evict/TaskEvictPolicyManager.java
> +            policyJsonStr = loadedPolicyJsonStr;
ok

2022-01-14 13:12 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +            return true;
ok

2022-01-14 13:12 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +            if (checkAndEvictTaskIfNeed(watch)) return;
ok

2022-01-14 13:12 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/result/AbstractResultHandleTask.java
> +    private boolean pullGSELogs(StopWatch watch) {
ok

2022-01-14 13:13 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/RedisConstants.java
> +    public static final String KEY_EXECUTE_TASK_EVICT_POLICY = "taskEvictPolicy";
ok

2022-01-14 13:13 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/exception/DefenseTriggeredException.java
> +        super(ErrorType.DEFENSE_TRIGGERED, errorCode);
ok

2022-01-14 13:17 UTC, wangyu096 requested changes

2022-01-14 13:17 UTC, wangyu096 commented on src/backend/commons/common/src/test/java/com/tencent/bk/job/common/util/StringUtilTest.java
> +    public void testIsChanged() {
testIsDifferent

2022-01-14 13:17 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/model/error/ErrorType.java
> +    DEFENSE_TRIGGERED(14);
多余的类型，需要删除

2022-01-14 13:35 UTC, jsonwan commented on src/backend/commons/common/src/test/java/com/tencent/bk/job/common/util/StringUtilTest.java
> +    public void testIsChanged() {
已修改

2022-01-14 13:35 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/model/error/ErrorType.java
> +    DEFENSE_TRIGGERED(14);
已删除

2022-01-14 14:05 UTC, wangyu096 approved these changes

2022-01-14 14:05 UTC, merged