bugfix: 解决高危语句规则的表达式在编辑时允许为空的问题 #587
Tencent/bk-job pull request #614
Opened 2022-01-11 09:22 UTC by smarttill-zyj

增加validation校验

2022-01-11 09:40 UTC, wangyu096 requested changes

2022-01-11 09:40 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=语法检测表达式不能为空
validation.constraints.InvalidJobHighRiskGrammarRegex_empty.message=语法检测表达式不能为空

2022-01-11 09:40 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=Job expression cannot be empty
英文翻译不准确。
validation.constraints.InvalidJobHighRiskGrammarRegex_empty.message=High-risk grammar regex can not be empty

2022-01-11 09:40 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en_US.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=Job expression cannot be empty
i18n key 命名不准确

2022-01-11 09:40 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_zh.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=语法检测表达式不能为空
i18n key 命名不准确

2022-01-11 09:40 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_zh_CN.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=语法检测表达式不能为空
i18n key 命名不准确

2022-01-11 09:40 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/AddOrUpdateDangerousRuleReq.java
> +    @NotNull(message = "{validation.constraints.InvalidJobRuleExpression_empty.message}")
i18n key 命名不准确

2022-01-12 02:08 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=Job expression cannot be empty
已更改

2022-01-12 02:08 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en_US.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=Job expression cannot be empty
已更改

2022-01-12 02:09 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_zh.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=语法检测表达式不能为空
已更改

2022-01-12 02:09 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_zh_CN.properties
> +validation.constraints.InvalidJobRuleExpression_empty.message=语法检测表达式不能为空
已更改

2022-01-12 02:09 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/AddOrUpdateDangerousRuleReq.java
> +    @NotNull(message = "{validation.constraints.InvalidJobRuleExpression_empty.message}")
已更改

2022-01-12 03:46 UTC, merged