bugfix: 高危脚本规则新建编辑操作，后端没有校验参数 #616
Tencent/bk-job pull request #625
Opened 2022-01-14 08:12 UTC by smarttillzyj

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidHandleAction_empty.message=处理动作不能为空
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidHandleAction_outOfRange.message=处理动作必须在{min}-{max}之间
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidRegularStatus_empty.message=规则启停状态不能为空
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidRegularStatus_outOfRange.message=规则启停状态必须在{min}-{max}之间
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/AddOrUpdateDangerousRuleReq.java
> +    @Range(min = 1L, max= 2L,
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/validation/common/Update.java
> +public interface Update {
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/validation/common/Create.java
> +
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/validation/common/Create.java
> +public interface Create {
已处理

2022-01-18 02:45 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/validation/common/Update.java
> +
已处理

2022-01-18 07:09 UTC, wangyu096 requested changes

2022-01-18 07:09 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/AddOrUpdateDangerousRuleReq.java
> +    @Size(min = 1, max= 2,
不能用Size，这个是要对枚举值进行校验，不是数值范围

2022-01-18 07:09 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidHighRiskGrammarHandleAction_outOfSize.message=处理动作值必须在{min}-{max}之间
提示有问题。直接改成“非法的处理动作”

2022-01-18 07:09 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidHighRiskRegularStatus_outOfSize.message=规则启停状态值必须在{min}-{max}之间
提示有问题

2022-01-18 08:49 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/AddOrUpdateDangerousRuleReq.java
> +    @Size(min = 1, max= 2,
已改枚举校验

2022-01-18 08:49 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidHighRiskGrammarHandleAction_outOfSize.message=处理动作值必须在{min}-{max}之间
已处理

2022-01-18 08:49 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidHighRiskRegularStatus_outOfSize.message=规则启停状态值必须在{min}-{max}之间
已处理

2022-01-18 09:56 UTC, wangyu096 requested changes

2022-01-18 09:56 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +                return Boolean.TRUE;
为什么要return Boolean.TRUE 而不是 return true ?

2022-01-18 09:56 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +                    throw new NotImplementedException("Not support method", ErrorCode.NOT_SUPPORT_FEATURE);
NOT_SUPPORT_FEATURE 指的是未上线的特性。不适用这里。 所有校验过程中发生的异常场景，建议统一使用InternalException(系统异常)

2022-01-18 09:56 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +                    throw new NotImplementedException("Not support method", ErrorCode.NOT_SUPPORT_FEATURE);
NOT_SUPPORT_FEATURE 不适用这里。 所有异常场景，建议可以统一返回false。

2022-01-18 09:56 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/common/consts/rule/HandleActionEnum.java
> +public enum HandleActionEnum {
HandleActionEnum 太笼统了，其他地方也有这个。建议改成HighRiskGrammarActionEnum

2022-01-18 09:56 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/common/consts/rule/HandleActionEnum.java
> +        for (HandleActionEnum userStatusEnum : HandleActionEnum.values()) {
userStatusEnum？？

2022-01-18 09:56 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/common/consts/rule/RuleUseStatusEnum.java
> +public enum RuleUseStatusEnum {
HighRiskGrammarRuleStatusEnum

2022-01-18 10:17 UTC, smarttillzyj commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +                return Boolean.TRUE;
已处理

2022-01-18 10:17 UTC, smarttillzyj commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +                    throw new NotImplementedException("Not support method", ErrorCode.NOT_SUPPORT_FEATURE);
已处理已处理

2022-01-18 10:18 UTC, smarttillzyj commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +                    throw new NotImplementedException("Not support method", ErrorCode.NOT_SUPPORT_FEATURE);
已处理

2022-01-18 10:18 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/common/consts/rule/HandleActionEnum.java
> +public enum HandleActionEnum {
已处理

2022-01-18 10:18 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/common/consts/rule/HandleActionEnum.java
> +        for (HandleActionEnum userStatusEnum : HandleActionEnum.values()) {
已处理

2022-01-18 14:53 UTC, wangyu096 requested changes

2022-01-19 03:00 UTC, smarttillzyj commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/validation/CheckEnum.java
> +@Constraint(validatedBy = NotBlankFieldValidator.class)
已处理

2022-01-19 08:09 UTC, wangyu096 approved these changes

2022-01-19 08:09 UTC, merged