feature: 业务集形态改造（平台内置转对接CMDB） #622
Tencent/bk-job pull request #672
Opened 2022-02-28 02:48 UTC by jsonwan

1.切面级”业务访问“权限鉴权改造
2.预鉴权接口改造

2022-02-28 08:34 UTC, wangyu096 requested changes

2022-02-28 10:25 UTC, jsonwan commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/web/WebPermissionResource.java
> -        @RequestParam(value = "appId", required = false) Long appId,
增加了自定义注解标识

2022-03-01 01:48 UTC, wangyu096 approved these changes

2022-03-01 01:48 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/interceptor/JobCommonInterceptor.java
> +    private static final Pattern SCOPE_TYPE_PATTERN = Pattern.compile("/scope_type/(\\w+)");
ok

2022-03-01 01:48 UTC, merged