feature: 业务集改造-cmdb业务、业务集与Job业务的转换 #676
Tencent/bk-job pull request #677
Opened 2022-03-02 12:15 UTC by wangyu096

1. 定义资源范围相关类(ResourceScope）
2. 结束iam-sdk中对于appId的处理，在应用层统一处理
3. 区分IAM ResourceType 与 Job ResouceScope的概念

注意：
构造IAM Path 的代码由于不清楚实现，暂时使用默认的方式。（已加TODO方便后续修改）

2022-03-02 12:40 UTC, jsonwan commented on src/backend/gradlew.bat
> +@rem Set local resourceScope for the variables with windows NT shell
误改？

2022-03-02 12:40 UTC, jsonwan commented on src/backend/gradlew.bat
> +@rem End local resourceScope for the variables with windows NT shell
误改？

2022-03-02 12:40 UTC, jsonwan commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=步骤
误改？

2022-03-02 12:40 UTC, jsonwan commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_en.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=Steps
误改？

2022-03-02 12:40 UTC, jsonwan commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_en_US.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=Steps
误改？

2022-03-02 12:41 UTC, jsonwan commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_zh.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=步骤
误改？

2022-03-02 12:41 UTC, jsonwan commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_zh_CN.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=步骤
误改？

2022-03-02 13:23 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebPermissionResourceImpl.java
> +                                                                      .getId(), buildScopePathInfo(resourceScope)));
换行格式注意下

2022-03-02 13:29 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/web/impl/WebPermissionResourceImpl.java
>      }
重构前后实现的功能不一致，业务集的需要考虑

2022-03-02 13:46 UTC, jsonwan requested changes

2022-03-02 13:46 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/web/impl/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeEnum.BUSINESS.getId(), resourceScope.getId()).build();
重构前后实现的功能不一致，业务集的需要考虑

2022-03-02 13:46 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/api/web/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId()).build();
需要补充兼容业务集的实现，重构前已兼容业务集

2022-03-02 13:46 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/ExecuteAuthServiceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId()).build();
需要补充兼容业务集的实现，重构前已兼容业务集

2022-03-02 13:46 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId()).build();
需要补充兼容业务集的实现，重构前已兼容业务集

2022-03-02 13:46 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId())
需要补充兼容业务集的实现，重构前已兼容业务集

2022-03-02 14:12 UTC, wangyu096 commented on src/backend/gradlew.bat
> +@rem Set local resourceScope for the variables with windows NT shell
嗯，我改回去。

2022-03-02 14:12 UTC, wangyu096 commented on src/backend/gradlew.bat
> +@rem End local resourceScope for the variables with windows NT shell
嗯，我改回去。

2022-03-02 14:15 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=步骤
fixed

2022-03-02 14:15 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_en.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=Steps
fixed

2022-03-02 14:15 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_en_US.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=Steps
fixed

2022-03-02 14:15 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_zh.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=步骤
fixed

2022-03-02 14:16 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/resources/i18n/message_zh_CN.properties
> +job.analysis.analysistask.result.AbnormalTargetPlanInfo.stepName.resourceScope.Step=步骤
fixed

2022-03-02 14:18 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebPermissionResourceImpl.java
> +                                                                      .getId(), buildScopePathInfo(resourceScope)));
fixed

2022-03-02 14:40 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId())
fixed

2022-03-02 14:40 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId()).build();
fixed

2022-03-02 14:40 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/ExecuteAuthServiceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId()).build();
fixed

2022-03-02 14:40 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/api/web/WebPermissionResourceImpl.java
> +        return PathBuilder.newBuilder(ResourceTypeId.BIZ, resourceScope.getId()).build();
fixed

2022-03-03 01:59 UTC, jsonwan approved these changes

2022-03-03 01:59 UTC, merged