perf: job-execute从job-manage拉取IP白名单生效表耗时过长 #663
Tencent/bk-job pull request #720
Opened 2022-03-18 07:27 UTC by smarttillzyj

2022-03-21 04:23 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
> +            List<ApplicationDTO> allAppSetList = allAppTypeGroupMap.get(AppTypeEnum.NORMAL);
枚举值使用错误，需改正

2022-03-21 04:26 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
> +                Collectors.groupingBy(ApplicationDTO::getOperateDeptId));
部门id为null的数据会被怎样分组，需要核实下

2022-03-21 04:31 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
>          //1.查找包含当前业务的业务集、全业务
先合并下master，解决编译不通过问题

2022-03-21 04:36 UTC, jsonwan requested changes
这里的实现只涉及一个内部调用方法，需要继续优化下listWhiteIPInfos方法中的实现。

2022-03-31 02:37 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
> +                Collectors.groupingBy(ApplicationDTO::getOperateDeptId));
已处理

2022-03-31 02:37 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
> +            List<ApplicationDTO> allAppSetList = allAppTypeGroupMap.get(AppTypeEnum.NORMAL);
已处理

2022-03-31 02:38 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
>          //1.查找包含当前业务的业务集、全业务
已处理

2022-03-31 02:38 UTC, smarttillzyj commented
listWhiteIPInfos方法已优化

2022-04-02 09:52 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            actionScopeDTOList.addAll(actionScopeDAO.getActionScopeByIds(idList));
循环当中查询DB，还可进一步优化

2022-04-02 10:16 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/ActionScopeDAOImpl.java
> +    public List<ActionScopeDTO> getActionScopeByIds(List<Long> scopeIdSet) {
参数名不准确，List类型参数用了Set命名

2022-04-02 10:16 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/ActionScopeDAO.java
> +    List<ActionScopeDTO> getActionScopeByIds(List<Long> scopeIdSet);
参数名称不准确

2022-04-02 10:21 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/ActionScopeDAOImpl.java
> +        val records = defaultDslContext.selectFrom(T_ACTION_SCOPE)
selectFrom是查询全部字段，效率低，并且会导致在有新增字段的表上编译后的代码运行在无新增字段表的环境中时报字段不存在错误，新增代码中不要有，老代码中遇到了就改掉

2022-04-02 10:23 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/ActionScopeDAOImpl.java
> +        if (records == null) {
null判断应该是多余的，看idea提示

2022-04-02 10:23 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPActionScopeDAOImpl.java
> +        if (records == null) {
null判断多余

2022-04-02 10:24 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPAppRelDAOImpl.java
> +        if (records == null) {
null判断多余

2022-04-02 10:24 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPIPDAOImpl.java
> +        if (records == null) {
null判断多余

2022-04-02 10:31 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPRecordDAOImpl.java
> +        val whiteIPRecord = dslContext.selectFrom(T_WHITE_IP_RECORD).fetch();
selectFrom改为指定具体字段

2022-04-02 11:35 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPRecordDAOImpl.java
> +        val whiteIPRecord = dslContext.selectFrom(T_WHITE_IP_RECORD).fetch();
变量名使用复数

2022-04-02 11:43 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
> +            List<ApplicationDTO> allAppSetList = allAppTypeGroupMap.get(AppTypeEnum.NORMAL);
我这边看到的还是用的NORMAL，再检查下？

2022-04-02 11:44 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +        recordList.parallelStream().forEach(d -> {
d这个变量名改成record

2022-04-02 11:47 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            if (d.getIpList().size() == 1) {
这里确定是getIpList?

2022-04-02 11:47 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
>              }
else语句呢？

2022-04-02 11:48 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +        });
上面这段代码的意图请加上注释

2022-04-02 12:00 UTC, jsonwan requested changes
提了一些问题需要再看下

2022-04-06 12:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ApplicationServiceImpl.java
> +            List<ApplicationDTO> allAppSetList = allAppTypeGroupMap.get(AppTypeEnum.NORMAL);
已处理

2022-04-06 12:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            actionScopeDTOList.addAll(actionScopeDAO.getActionScopeByIds(idList));
in最大查询为1000，变量名已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/ActionScopeDAOImpl.java
> +    public List<ActionScopeDTO> getActionScopeByIds(List<Long> scopeIdSet) {
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/ActionScopeDAO.java
> +    List<ActionScopeDTO> getActionScopeByIds(List<Long> scopeIdSet);
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/ActionScopeDAOImpl.java
> +        val records = defaultDslContext.selectFrom(T_ACTION_SCOPE)
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/ActionScopeDAOImpl.java
> +        if (records == null) {
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPActionScopeDAOImpl.java
> +        if (records == null) {
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPAppRelDAOImpl.java
> +        if (records == null) {
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPIPDAOImpl.java
> +        if (records == null) {
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/whiteip/impl/WhiteIPRecordDAOImpl.java
> +        val whiteIPRecord = dslContext.selectFrom(T_WHITE_IP_RECORD).fetch();
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +        recordList.parallelStream().forEach(d -> {
已处理

2022-04-06 12:23 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +            if (d.getIpList().size() == 1) {
已处理

2022-04-06 12:24 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
>              }
只有长度为1是才需要处理

2022-04-06 12:24 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/WhiteIPServiceImpl.java
> +        });
已处理

2022-04-20 13:17 UTC, jsonwan approved these changes

2022-04-20 13:17 UTC, merged