bugfix: v3_get_cron_list接口在指定ID查询单个定时任务时报错 #754
Tencent/bk-job pull request #755
Opened 2022-03-28 14:06 UTC by jsonwan

2022-03-28 15:08 UTC, wangyu096 requested changes

2022-03-28 15:08 UTC, wangyu096 commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/esb/v3/impl/EsbCronJobV3ResourceImpl.java
> +                    esbPageDataV3.setTotal(0L);
total不是应该等于实际查询到的数量么，有可能等于1。start和length似乎应该返回用户传入的，如果为空使用默认值吧？

2022-03-29 02:04 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/esb/v3/impl/EsbCronJobV3ResourceImpl.java
> +                    esbPageDataV3.setTotal(0L);
这里是指定ID查询单个定时任务的分支，不过这种方式确实不好，改为默认值设置前置的方式了。

2022-03-29 02:22 UTC, wangyu096 approved these changes

2022-03-29 02:22 UTC, merged