feature: 业务集改造-问题修复、代码重构 #728
Tencent/bk-job pull request #758
Opened 2022-03-30 07:35 UTC by wangyu096

1. ESB API bk_biz_id 参数兼容开关

2022-03-30 07:41 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/interceptor/JobCommonInterceptor.java
> +        if (StringUtils.isNotBlank(scopeType) || StringUtils.isNotBlank(scopeId)) {
这里是&&才是有效的Scope数据

2022-03-30 07:44 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/EsbAppScopeReq.java
> +        boolean isExistScopeParam = StringUtils.isNotEmpty(this.scopeType) ||
同上一处，type和id只存在一个是无效的吧

2022-03-30 07:46 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/EsbAppScopeReq.java
> -                new String[]{"bk_biz_id/bk_scope_type/bk_scope_id"});
这里的else分支处理去掉的原因？两种参数都不存在的情况不需要提示而是直接500？

2022-03-30 07:50 UTC, jsonwan requested changes
部分地方的处理可能不合理，再确认下

2022-03-30 08:07 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/EsbAppScopeReq.java
> -                new String[]{"bk_biz_id/bk_scope_type/bk_scope_id"});
spring validation 有校验，不存在else的情况

2022-03-30 08:10 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/interceptor/JobCommonInterceptor.java
> +        if (StringUtils.isNotBlank(scopeType) || StringUtils.isNotBlank(scopeId)) {
|| 才是正确的行为，inteceptor调用优先与参数校验，所以可能存在用户没传入所有参数的情况。具体的处理会放到参数校验那里

2022-03-30 08:13 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/EsbAppScopeReq.java
> +        boolean isExistScopeParam = StringUtils.isNotEmpty(this.scopeType) ||
理论上调用到这行，scopeType和scopeId都是存在的。但是isExistScopeParam是表示存在scope相关的参数中的一个，就会走下面的使用scope的分支，而不是走bk_biz_id的分支

2022-03-30 08:36 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/interceptor/JobCommonInterceptor.java
> +        if (StringUtils.isNotBlank(scopeType) || StringUtils.isNotBlank(scopeId)) {
已沟通，使用||会导致业务访问鉴权处报500，此处应使用&&

2022-03-31 10:23 UTC, jsonwan approved these changes

2022-03-31 11:48 UTC, merged