perf: 高危语句规则实时生效 #750
Tencent/bk-job pull request #773
Opened 2022-04-02 07:01 UTC by smarttillzyj

2022-04-06 09:06 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(req.getScriptTypeList());
这里似乎不需要删除两次缓存吧，直接处理完之后最后一行删除缓存数据就可以了

2022-04-06 09:07 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(DangerousRuleDTO.decodeScriptType(existDangerousRuleDTO.getScriptType()));
调整规则的优先级，应该会影响到其他的规则，而不是只有当前规则

2022-04-06 09:07 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(DangerousRuleDTO.decodeScriptType(existDangerousRuleDTO.getScriptType()));
调整规则的优先级，应该会影响到其他的规则，而不是只有当前规则

2022-04-06 09:08 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +        Object appObj = redisTemplate.opsForHash().get("job:manage:dangerousRules", String.valueOf(scriptType));
appObj，这个命名有问题吧?

2022-04-06 09:08 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +        Object appObj = redisTemplate.opsForHash().get("job:manage:dangerousRules", String.valueOf(scriptType));
appObj，这个命名有问题吧?

2022-04-06 09:11 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return null;
直接return null这个逻辑不对。如果用户没有定义该脚本类型的任何规则，那么应该在缓存里边存的值是一个空的集合。如果这里直接return null,那么下一次请求还是要走查询DB的逻辑，带来了不必要的开销。

2022-04-06 09:11 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return null;
直接return null这个逻辑不对。如果用户没有定义该脚本类型的任何规则，那么应该在缓存里边存的值是一个空的集合。如果这里直接return null,那么下一次请求还是要走查询DB的逻辑，带来了不必要的开销。

2022-04-06 09:12 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                    BeanUtils.copyProperties(d, dangerousRuleDO);
不要使用BeanUtils，容易出问题。万一变量名变了，错误没法在编译期检测到。建议直接写DTO转换的方法

2022-04-06 09:12 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                    BeanUtils.copyProperties(d, dangerousRuleDO);
不要使用BeanUtils，容易出问题。万一变量名变了，错误没法在编译期检测到。建议直接写DTO转换的方法

2022-04-06 09:12 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                log.warn("Refresh dangerousRules cache fail", e);
error级别的日志更合适

2022-04-06 09:12 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                log.warn("Refresh dangerousRules cache fail", e);
error级别的日志更合适

2022-04-06 09:13 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +            BeanUtils.copyProperties(d, dangerousRuleDTO);
建议不要用BeanUtils

2022-04-06 09:13 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +            BeanUtils.copyProperties(d, dangerousRuleDTO);
建议不要用BeanUtils

2022-04-06 09:13 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(req.getScriptTypeList());
删除的逻辑似乎还没有处理?

2022-04-06 09:13 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(req.getScriptTypeList());
删除的逻辑似乎还没有处理?

2022-04-07 06:21 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(DangerousRuleDTO.decodeScriptType(existDangerousRuleDTO.getScriptType()));
已处理

2022-04-07 06:21 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(req.getScriptTypeList());
> 这里似乎不需要删除两次缓存吧，直接处理完之后最后一行删除缓存数据就可以了
已处理
> 删除的逻辑似乎还没有处理?
缓存删除逻辑已经处理了的

2022-04-07 06:21 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(DangerousRuleDTO.decodeScriptType(existDangerousRuleDTO.getScriptType()));
同上

2022-04-07 06:21 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +        Object appObj = redisTemplate.opsForHash().get("job:manage:dangerousRules", String.valueOf(scriptType));
已处理

2022-04-07 06:21 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +        Object appObj = redisTemplate.opsForHash().get("job:manage:dangerousRules", String.valueOf(scriptType));
同上

2022-04-07 06:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                    BeanUtils.copyProperties(d, dangerousRuleDO);
已处理

2022-04-07 06:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                log.warn("Refresh dangerousRules cache fail", e);
已处理

2022-04-07 06:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                log.warn("Refresh dangerousRules cache fail", e);
同上

2022-04-07 06:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +            BeanUtils.copyProperties(d, dangerousRuleDTO);
已处理

2022-04-07 06:22 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +            BeanUtils.copyProperties(d, dangerousRuleDTO);
同上

2022-04-08 01:41 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return null;
已处理

2022-04-08 01:41 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                    BeanUtils.copyProperties(d, dangerousRuleDO);
已处理

2022-04-08 02:37 UTC, wangyu096 requested changes

2022-04-08 02:37 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return new ArrayList<DangerousRuleDTO>();
需要刷新缓存，不然下一次查询还是需要从MySQL查询数据

2022-04-08 05:52 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/DangerousRuleServiceImpl.java
> +        deleteDangerousRuleCacheByScriptTypes(req.getScriptTypeList());
已处理

2022-04-08 06:01 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return new ArrayList<DangerousRuleDTO>();
已处理

2022-04-08 07:03 UTC, wangyu096 requested changes

2022-04-08 07:03 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return new ArrayList<DangerousRuleDTO>();
可以再优化下，不要new ArrayList两次

2022-04-08 07:37 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return new ArrayList<DangerousRuleDTO>();
两个对象不一样的，一个是存redis（DangerousRuleDO）一个是返回调用方的（DangerousRuleDTO）

2022-04-08 08:49 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptCheckServiceImpl.java
> +                return new ArrayList<DangerousRuleDTO>();
ok

2022-04-08 08:49 UTC, wangyu096 approved these changes

2022-04-08 08:49 UTC, merged