feature: 新增本地文件上传的后缀配置管理能力 #743
Tencent/bk-job pull request #789
Opened 2022-04-07 06:38 UTC by smarttillzyj

2022-04-07 09:01 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +        }
这里的后缀名限制导致方法特别长，建议重构，把这个检查单独写一个方法

2022-04-07 09:02 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +        InternalResponse<FileUploadSettingVO> resp = globalSettingsClient.getFileUploadSettings(userName);
这个全局设置应该跟用户没关系，为啥需要username参数?

2022-04-07 09:14 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +        Boolean validateSuffix = true;
Boolean -> boolean

2022-04-07 09:15 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/inner/ServiceGlobalSettingsResource.java
> +    InternalResponse<FileUploadSettingVO> getFileUploadSettings(@RequestHeader("username") String username);
这里可能不一定需要username？

2022-04-07 09:16 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/inner/ServiceGlobalSettingsResource.java
> +    @GetMapping("/getFileUploadSettings")
getFileUploadSettings不是规范的restful API path，改成名词格式的，不要用动词。比如fileUploadSettings

2022-04-07 09:22 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/FileUploadSettingReq.java
> +                @Pattern(regexp = "^\\.[A-Za-z]{1,24}$", message = "{validation.constraints.InvalidFileSuffix.message}") String> suffixList;
1. 这个注解的方式确定校验可以生效么？
2. 换行不对

2022-04-07 09:47 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +                            validateSuffix = true;
这段代码虽然能够达到效果，但是写的不好理解。建议分别处理ALLOW和FORBIDDEN的情况

2022-04-07 09:47 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +        if (CollectionUtils.isNotEmpty(suffixList)) {
为啥需要初始状态?

2022-04-07 09:48 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +            log.warn("Fast send file, file suffix not allow");
这个日志有问题

2022-04-07 09:49 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +                        } else {
不要直接else，万一以后引入第三种限制模式，这里的处理就有问题了。针对FORBIDDEN处理

2022-04-07 09:52 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/GlobalSettingsServiceImpl.java
> +            new UploadFileRestrictDto(
存入到db的对象，必须是DO，防止后面修改UploadFileRestrictDTO中的字段名的时候，导致异常的情况

2022-04-07 09:53 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/GlobalSettingsServiceImpl.java
>      public FileUploadSettingVO getFileUploadSettings(String username) {
这个username是多余的?

2022-04-08 05:41 UTC, smarttillzyj commented on support-files/sql/job-manage/0024_job_manage_20211230-1000_V3.4.6.0_mysql.sql
> +update `global_setting` set `key`='FILE_UPLOAD_SETTING',`value`=CONCAT('{"maxSize":"',`value`,'"}'),`decription`='setting of upload file'
已处理

2022-04-08 05:41 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/GlobalSettingsServiceImpl.java
> +                throw new InvalidParamException(ErrorCode.UPLOAD_FILE_SUFFIX_NOT_ALLOW_REPEAT);
已处理

2022-04-08 05:41 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/model/dto/globalsetting/UploadFileRestrictDto.java
> +public class UploadFileRestrictDto {
已处理

2022-04-08 05:41 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/model/dto/globalsetting/UploadFileRestrictDto.java
> +
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_zh_CN.properties
> +validation.constraints.InvalidRestrictMode.message=非法的限制模式
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/constant/ErrorCode.java
> +    public static final int UPLOAD_FILE_SUFFIX_NOT_ALLOW_REPEAT = 1243050;
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/commons/common-i18n/src/main/resources/i18n/exception/message_en.properties
> +1243050=File suffix not allow repeat
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +        }
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +        InternalResponse<FileUploadSettingVO> resp = globalSettingsClient.getFileUploadSettings(userName);
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +        Boolean validateSuffix = true;
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/inner/ServiceGlobalSettingsResource.java
> +    @GetMapping("/getFileUploadSettings")
已处理

2022-04-08 05:42 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/FileUploadSettingReq.java
> +                @Pattern(regexp = "^\\.[A-Za-z]{1,24}$", message = "{validation.constraints.InvalidFileSuffix.message}") String> suffixList;
已处理

2022-04-08 05:43 UTC, smarttillzyj commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/request/globalsetting/FileUploadSettingReq.java
> +                @Pattern(regexp = "^\\.[A-Za-z]{1,24}$", message = "{validation.constraints.InvalidFileSuffix.message}") String> suffixList;
可以生效

2022-04-08 05:43 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +                            validateSuffix = true;
已处理

2022-04-08 05:43 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +        if (CollectionUtils.isNotEmpty(suffixList)) {
说明已加上

2022-04-08 05:43 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +            log.warn("Fast send file, file suffix not allow");
已处理

2022-04-08 05:43 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebFileUploadResourceImpl.java
> +                        } else {
已处理

2022-04-08 05:46 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/GlobalSettingsServiceImpl.java
> +            new UploadFileRestrictDto(
这个是数据交换对象，跟服务传输对象统一，应该合理的，整个manage跟数据库交换也是DTO

2022-04-08 05:46 UTC, smarttillzyj commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/GlobalSettingsServiceImpl.java
>      public FileUploadSettingVO getFileUploadSettings(String username) {
已处理

2022-04-08 09:38 UTC, wangyu096 requested changes

2022-04-08 09:38 UTC, wangyu096 commented on support-files/sql/job-manage/0024_job_manage_20211230-1000_V3.4.6.0_mysql.sql
> +DROP PROCEDURE IF EXISTS job_data_update;
没有换行

2022-04-08 09:38 UTC, wangyu096 commented on support-files/sql/job-manage/0024_job_manage_20211230-1000_V3.4.6.0_mysql.sql
> +		DELETE FROM `global_setting` WHERE `key` = 'FILE_UPLOAD_MAX_SIZE';
DELETE 缩进错误

2022-04-08 10:10 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +            if (CollectionUtils.isNotEmpty(suffixList)) {
这一段代码嵌套太多了，可以改成先判断isEmpty()然后continue，能减少一层嵌套

2022-04-08 10:12 UTC, jsonwan reviewed
增加一个建议

2022-04-08 10:13 UTC, smarttillzyj commented on support-files/sql/job-manage/0024_job_manage_20211230-1000_V3.4.6.0_mysql.sql
> +DROP PROCEDURE IF EXISTS job_data_update;
已处理

2022-04-08 10:13 UTC, smarttillzyj commented on support-files/sql/job-manage/0024_job_manage_20211230-1000_V3.4.6.0_mysql.sql
> +		DELETE FROM `global_setting` WHERE `key` = 'FILE_UPLOAD_MAX_SIZE';
已处理

2022-04-08 10:44 UTC, smarttillzyj commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +            if (CollectionUtils.isNotEmpty(suffixList)) {
已处理

2022-04-11 02:56 UTC, smarttillzyj commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +            if (CollectionUtils.isNotEmpty(suffixList)) {
suffixList如果为空，可以直接跳出循环，肯定不会执行里面去

2022-04-11 02:56 UTC, smarttillzyj commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebExecuteTaskResourceImpl.java
> +            if (CollectionUtils.isNotEmpty(suffixList)) {
suffixList如果为空，可以直接跳出循环，肯定不会执行里面去

2022-04-11 09:43 UTC, merged