feature: IP选择器支持以hostId作为主机唯一标识进行交互 #978
Tencent/bk-job pull request #988
Opened 2022-06-02 10:02 UTC by jsonwan

1. checkHosts接口改造，接口参数增加hostId；
2. 增加通过拓扑节点、筛选条件查hostId的接口，将老的查IP的接口标记为兼容实现，未来将移除。

2022-06-03 01:00 UTC, wangyu096 requested changes

2022-06-03 01:00 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/StringUtil.java
>          if (str == null || str.isEmpty() || StringUtils.isBlank(str)) {
str == null || str.isEmpty()的判断是多余的，StringUtils.isBlank 已经包含上述判断

2022-06-03 01:00 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/common/util/StringParamUtil.java
> +     * 使用常见的分号、逗号、换行、空格等字符分割字符串
注释不够准确。建议把“分号、逗号、换行、空格等字符” 改为具体支持的分隔符

2022-06-03 01:00 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +                .set(TABLE.IP_V6, applicationHostDTO.getIpv6())
IPV6是不是也有可能会发生变化?在IP漂移的场景下

2022-06-03 01:00 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/HostTopoDAOImpl.java
> +        if (bizIds != null) {
!= null 应该要改成isNotEmpty, 否则sql执行会报错

2022-06-03 01:00 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/HostTopoDAOImpl.java
> +        if (hostIds != null) {
!= null 应该要改成isNotEmpty, 否则sql执行会报错

2022-06-06 03:08 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/StringUtil.java
>          if (str == null || str.isEmpty() || StringUtils.isBlank(str)) {
已修改

2022-06-06 03:10 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/WebAppResource.java
> +    @PostMapping(value = {"/scope/{scopeType}/{scopeId}/ip/check", "/scope/{scopeType}/{scopeId}/host/check"})
已加

2022-06-06 03:13 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/common/util/StringParamUtil.java
> +     * 使用常见的分号、逗号、换行、空格等字符分割字符串
已修改

2022-06-06 03:13 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/common/util/StringParamUtil.java
> +public class StringParamUtil {
已修改

2022-06-06 08:33 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/HostTopoDAOImpl.java
> +        if (hostIds != null) {
已修改

2022-06-06 08:33 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/HostTopoDAOImpl.java
> +        if (bizIds != null) {
已修改

2022-06-06 08:35 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +                .set(TABLE.IP_V6, applicationHostDTO.getIpv6())
当面沟通对齐。

2022-06-06 08:48 UTC, wangyu096 approved these changes

2022-06-06 08:48 UTC, merged